### ISSUE TITLE
Cache update does not rerender

### ISSUE THREAD

**Issue by john-dominguez** [ecerroni/apollo-cache-updater#13]
## Issue:
When adding a new Employee, ApolloCacheUpdater successfully updates the cache but does not trigger a re-render ( shown once the page is refreshed).

## Info:
**REMOVE** is working as intended and triggers a re-render upon completion.

### Client Options:
```
fetchPolicy: 'cache-and-network',
errorPolicy: 'all',
notifyOnNetworkStatusChange: true,
returnPartialData: true
```

## Image
The following image shows:
1. **Console log**: Created Employee & ApolloCacheUpdater ran successfully
2. **Apollo Extension**: Shows the Employee in cache
3. **Table**: Empty table
4. **employees object**: data object from `const { loading, data, refetch } = useQuery(GET_EMPLOYEES)`

![Image](https://i.imgur.com/jaHUtwN.png)

**Comment by john-dominguez** [comment]
Solved:
Setting the fetchPolicy to 'cache-first' fixed the issue.

**Comment by john-dominguez** [comment]
There's an edge case of when the table is empty and you create a new item it does not force a UI Update.

**Comment by john-dominguez** [comment]
There's an edge case of when the table is empty and you create a new item it does not force a UI Update.

**Comment by ecerroni** [comment]
@john-dominguez if you create a small repo reproducing the issue I'll be happy to have a look  :+1:

**Comment by john-dominguez** [comment]
> @john-dominguez if you create a small repo reproducing the issue I'll be happy to have a look 👍

Apologies, i couldn't figure out why it wasn't initially working. It is fixed now that i changed my rendering.
