### ISSUE TITLE
Generally confused on how this package works

### ISSUE THREAD

**Issue by ffxsam** [ecerroni/apollo-cache-updater#5]
I currently have this in my code:

```js
update: (store, { data: { deleteTracks } }) => {
  const updates = ApolloCacheUpdater({
    proxy: store,
    queriesToUpdate: [getTracksQuery],
    searchVariables: {
      // ??
    },
    mutationResult: deleteTracks,
  });
},
```

It just so happens that my delete mutation returns an array of IDs that were actually found and deleted, but the cache updater doesn't like this:

`ApolloCacheUpdater Error: mutationResult cannot be an array | [mutation-result_no-array]`

I'm also not totally sure I'm using `searchVariables` properly.

**Comment by ffxsam** [comment]
More info about my queries:

### getTracksQuery
```gql
query GetTracks(
  $limit: Int
  $offset: Int
  $sort: String
  $order: String
  $search: String
) {
  getTracks(
    options: {
      limit: $limit
      offset: $offset
      sort: $sort
      order: $order
      search: $search
    }
  ) {
    total
    data {
      id
      name
      runtime
      createdAt
      metadata {
        trackNum
        trackName
        artistName
        albumName
        year
      }
    }
  }
}
```

### deleteTracks
```gql
mutation DeleteTracks($ids: [Int!]!) {
  deleteTracks(ids: $ids)  # returns an array of deleted IDs
}
```

**Comment by ecerroni** [comment]
Hey @ffxsam 

Let's fix it one by one:
`ApolloCacheUpdater Error: mutationResult cannot be an array | [mutation-result_no-array]`

Yes, the above is a requirement for `mutationResult`: 
- it should be a single object
- it should contain an unique identifier. `id` is the default

In your case, because you're returning an array of ids as the mutation result you need to iterate the array and delete the item one by one. There is no other way. 

Another thing you need to do is to specify the operation type. If not specified it deafults to `ADD`. That is not what you want. Indeed you need `REMOVE`.

```
const updates = deleteTracks.map(trackId => ApolloCacheUpdater({
    proxy: store,
    operation: 'REMOVE',
    queriesToUpdate: [getTracksQuery],
    searchVariables: {
      ...
    },
    mutationResult: { id: trackId },
  }));
```
Looking at your code, regarding the `searchVariables` you have 2 options:

1. If the `sort` field is the same across any possible query variables combinations I would use the following:
```
const updates = deleteTracks.map(trackId => ApolloCacheUpdater({
    proxy: store,
    operation: 'REMOVE',
    queriesToUpdate: [getTracksQuery],
    searchOperator: 'OR', // OR means as soon as it finds `sort: 'createdAt'` it'll pick up the cached query without trying matching about other possible vars.
    searchVariables: {
       sort: 'createdAt',
    },
   mutationResult: { id: trackId },
  }));
```

2. As if I understood correctly you want to update all `getTracksQuery` without the need to discriminate based on query vars I'd suggest using the @connection directive in your original query to specify a store key for parts of your queries so that you can later pass then an empty searchVariables object.
Your Query:
```
query GetTracks(
  $limit: Int
  $offset: Int
  $sort: String
  $order: String
  $search: String
) @connection(key: "tracks") {
  getTracks(
    options: {
      limit: $limit
      offset: $offset
      sort: $sort
      order: $order
      search: $search
    }
  ) {
    total
    data {
      id
      name
      runtime
      createdAt
      metadata {
        trackNum
        trackName
        artistName
        albumName
        year
      }
    }
  }
}
```

Your update:
```
const updates = deleteTracks.map(trackId => ApolloCacheUpdater({
    proxy: store,
    operation: 'REMOVE',
    queriesToUpdate: [getTracksQuery],
    searchVariables: {},
    mutationResult: { id: trackId },
  }));
```
More on the @connection directive
https://www.apollographql.com/docs/react/features/pagination.html#connection-directive

I wrote this from the top of my mind, the code might not be sound. Let me know if any of them worked for you.

**Comment by ffxsam** [comment]
>1. If the `sort` field is the same across any possible query variables combinations I would use the following:

Unfortunately, sort will not always be the same. All of these can potentially change: `sort`, `order`, `search`, `limit`, `offset`.

Also, I tried `@connection(key: "tracks")` but it made it so sorting in my table stopped working (because it's now ignoring those fields so it thinks the data hasn't changed).

I tried option #1, with mapping through track IDs and calling the cache updater. I get this error:

```
Error: Can't find field getTracks({"options":{}}) on object {
  "getTracks({\"options\":{\"order\":\"desc\",\"search\":\"\",\"sort\":\"createdAt\"}})": {
    "type": "id",
    "generated": true,
    "id": "$ROOT_QUERY.getTracks({\"options\":{\"order\":\"desc\",\"search\":\"\",\"sort\":\"createdAt\"}})",
    "typename": "TrackList"
  },
  "getTracks({\"options\":{\"order\":\"asc\",\"search\":\"\",\"sort\":\"createdAt\"}})": {
    "type": "id",
    "generated": true,
    "id": "$ROOT_QUERY.getTracks({\"options\":{\"order\":\"asc\",\"search\":\"\",\"sort\":\"createdAt\"}})",
    "typename": "TrackList"
  }
}.
    at readFromStore.js:77
```

**Comment by ffxsam** [comment]
It would be great if the updater could just go through the matching query names (`getTracks`), ignoring any variables, and just remove the IDs in question. E.g.:

![image](https://user-images.githubusercontent.com/12532733/53278591-c273a600-36cf-11e9-9384-7d6dc9a89f20.png)

**Comment by ecerroni** [comment]
@ffxsam I pushed a new version of the lib that addresses your use case.

The code you should use is:
```
const updates = deleteTracks.map(trackId => ApolloCacheUpdater({
    proxy: store,
    operator: 'ANY', // go through the matching query names (`getTracks`) ignoring any variables
    operation: 'REMOVE',
    queriesToUpdate: [getTracksQuery],
    searchVariables: {},
    mutationResult: { id: trackId },
  }));
```

Feel free to open this issue again if the fix does not work as expected;

**Comment by ffxsam** [comment]
I get this error a few times:

```
Error: Can't find field getTracks({"options":{}}) on object {
  "getTracks({\"options\":{\"order\":\"desc\",\"search\":\"\",\"sort\":\"createdAt\"}})": {
    "type": "id",
    "generated": true,
    "id": "$ROOT_QUERY.getTracks({\"options\":{\"order\":\"desc\",\"search\":\"\",\"sort\":\"createdAt\"}})",
    "typename": "TrackList"
  },
  "getTracks({\"options\":{\"order\":\"asc\",\"search\":\"\",\"sort\":\"createdAt\"}})": {
    "type": "id",
    "generated": true,
    "id": "$ROOT_QUERY.getTracks({\"options\":{\"order\":\"asc\",\"search\":\"\",\"sort\":\"createdAt\"}})",
    "typename": "TrackList"
  }
}.
```

Error points to this line:
https://github.com/ecerroni/apollo-cache-updater/blob/master/src/index.js#L287

**Comment by ffxsam** [comment]
PS, thank you for making those changes! This will solve a huge and popular use case (sorting tables of data).

**Comment by ecerroni** [comment]
So is it not working at all. is it just working at times or is it working but you're also getting the error messagr?

**Comment by ffxsam** [comment]
It never works (the cache never gets updated).

**Comment by ecerroni** [comment]
I see. Can you set up a demo repo in order to replicate the issue? Using mock data would be fine too.

There is probably something I'm missing from here.

**Comment by ffxsam** [comment]
Sure! This will also help me see if maybe there's something else wrong in my code. Give me a bit.

**Comment by ffxsam** [comment]
Here you go: https://github.com/ffxsam/repro-apollo-cache-updater

**Comment by ffxsam** [comment]
You can add more tracks via the Apollo DevTools extension.

```gql
mutation {
  createTrack(name: "Track Name") {
    id
  }
}
```

**Comment by ecerroni** [comment]
There are 3 factors at play here:
- Vue (although that should not be a problem at all)
- AWSAppSyncClient (I guess this might be the main culprit)
- TrackList is actually an object and not an array (did not realize it initially when I addressed this issue)

There is a test suite in place based on react-apollo, apollo-client and apollo-cache-inmemory. Although Vue is a different framework I think that does not make any difference so I'd rule out it as a possible issue.

The query matched returns an object and not an array as I mistakenly overlooked the first time. That means that the automatic list updates provided by this package are not applied and you need to pass a custom 'remove' function with your own custom logic. This is because with objects there is no way to predict standard behavior so a custom function is mandatory. The lib has this covered. So no problem with this.

I think that although AWSAppSyncClient heavy relies on Apollo Client it may slightly differ in some settings that can break this package.

For instance, what is this `options` field. Is it a specific query argument of AWSAppSyncClient when querying things? I did not find anything on their docs and without seeing the server query resolvers I can only guess what `options` might be. Or is it just a pattern of yours?

I am talking about this:
```
query GetTracks(
  $limit: Int
  $offset: Int
  $sort: String
  $order: String
  $search: String
) {
  getTracks(
    options: {
      limit: $limit
      offset: $offset
      sort: $sort
      order: $order
      search: $search
    }
  ) {
//
}
```

**Comment by ffxsam** [comment]
The `options` argument as an object is standard GraphQL:
https://graphql.org/graphql-js/mutations-and-input-types/

It's an input type, although now that I think about it, I probably don't need it at all. I could just do:

```gql
getTracks(limit: $limit, offset: $offset, ...etc)
```

I'll change that so it's a bit simpler. And you're right, as far as what `getTracks` returns, it returns a total count of items available, and then `items` is the array of actual records. So in the cache, for a deletion, the `total` would need to be decreased by one, and then the items would be updated to remove the item being deleted. I assume I'd do something like this?

```js
operation: {
  type: 'REMOVE',
  remove: ({ query, type, data, variables }) => {
    // ???
  },
},
```

**Comment by ecerroni** [comment]
Yes, you're right. However the package assumes a correspondence between operation's params and query's params. It's just a convention. Thus the following should work already:
```
query GetTracks(
  $limit: Int
  $offset: Int
  $sort: String
  $order: String
  $search: String
) {
  getTracks(
     limit: $limit
     offset: $offset
     sort: $sort
     order: $order
     search: $search
  ) { ... }

// OR
query GetTracks(
  $options: inputOptionsObj
) {
  getTracks(
     options: $options
  ) { ... }

```
I could manage to add another param to the ApolloCacheUpdater to handle cases like yours, but I am afraid I'd only add unnecessary complexity to a configuration object already pretty filled. I'll add a note to the Readme instead so other devs are aware of it, too.

So you should be ready to go with this custom remove function. I tested it locally and it worked:
```
const updates = deleteTracks.map(id =>
            ApolloCacheUpdater({
              proxy: store,
              operator: 'ANY',
              operation: {
                type: 'REMOVE',
                remove: ({ query, type, data, variables }) => {
                  if (query === 'getTracks' && type === 'object') {
                    const newData = {
                        ...data,
                        items: data.items.filter(item => item.id !== trackId),
                      }
                      return newData;
                  }
                  return data
                },
              },
              queriesToUpdate: [getTracksQuery],
              searchVariables: {},
              mutationResult: { id },
            })
          );
```

**Comment by ffxsam** [comment]
Thank you!! I'll give it a shot in a bit here. Now I remember why I used input types.

```gql
input SelectOptions {
  limit: Int
  offset: Int
  sort: String
  order: String
  search: String
}
```

This way I could use the same arguments for several different read operations on different models. `getTracks`, `getUsers`, etc. I'm not great at GraphQL, so I don't know if you can use fragments as query arguments.

**Comment by ecerroni** [comment]
That's ok :) Graphql is flexible and let you do exactly that.

However for this package to make it work (consider it a sort of limitation) you should have:
```
query GetTracks($options: SelectOptions) {
  getTracks(options: $options) { ... }
```
And you should be still able to call it in your Vue component as before:
```
data() {
    return {
      defaultSort: ['createdAt', 'desc'],
      query: getTracksQuery,
      queryVars: {
        order: 'desc',
        search: '',
        sort: 'createdAt',
      },
    }
  },

```

The most important thing is that with the ANY operator and the custom remove function I pasted in my precious comment is updating the local cache as needed for your use case.

**Comment by ffxsam** [comment]
Ah, you're right, I was mixing argument types between the query name and the query itself.

I'll mess around with my schema some more and optimize it, it could use some clean-up. Thanks again, this package is a life-saver! Kinda crazy the Apollo team didn't consider this when designing the cache. I did find this:

https://www.apollographql.com/docs/react/features/pagination.html#connection-directive

but I couldn't get it working with my table sorting. It just made it so changing sort column and order would not fetch from the server because all the different permutations use the same cache object. Seems it could be a bug: https://github.com/apollographql/apollo-client/issues/3228

**Comment by ffxsam** [comment]
I spoke too soon, it works most of the time, but there's some random edge case where it doesn't.

![screencap](https://user-images.githubusercontent.com/12532733/53302800-04affb00-3828-11e9-9df8-48d5dafed224.gif)

I'm not even sure why this would happen. And oddly enough, it doesn't happen all the time. If I reload the page, and fill up the cache w/ the four different combinations (created desc, created asc, name desc, name asc), sometimes it works. I can see the cache is indeed being updated just fine, but Apollo refuses to fetch from the cache even though the query vars are changing. Probably an Apollo bug.

**Comment by ecerroni** [comment]
I tried that in the demo repo and it works. If I re-sort rows after deletion it works all the time (despite if the query is in the cache or it has to fire a new call to the endpoint). Apollo cache updates as expected.

I know that is a simple example so it is a subset of your actual component tree, but as soon as the cache updates the components should mirror those changes. 

`react-apollo` re-renders, while `vue-apollo` is reactive, so in both cases queries should fetch.

However I worked with both Vue and React and there is an important difference between them on how they handle parent props.

- React re-renders children every time a prop changes
- Vue does not re-render children if a prop change (you need to use a computed property for that)

Is it possible that this is what is happening in your case (you're passing down props that probably do not trigger)?. Just an idea.

**Comment by ffxsam** [comment]
Yeah, I'm not sure what's going on, but either way, apollo-cache-updater is doing its job and working great. Thanks again for working on this!
