### ISSUE TITLE
Not working with @client directive

### ISSUE THREAD

**Issue by richieroldan** [ecerroni/apollo-cache-updater#6]
Hi! First of all thank you for this awesome helper.

I'm just having trouble making it work with @client directive. Below is my query

```javascript
const TODO_MANY = gql`
  query {
    todoMany {
      _id
      title
      isOptimistic @client
    }
  }
`;

const ADD_TODO = gql`
  mutation TodoCreateOne($input: CreateOneTodoInput!) {
    todoCreateOne(record: $input) {
      record {
        _id
        title
      }
      recordId
    }
  }
`;

```

Here's my onClick callback
```javascript
const onClick = useCallback(() => {
    const id = uuid();
    addTodo({
      variables: {
        input: {
          title: 'test12',
        },
      },
      optimisticResponse: {
        __typename: 'Mutation',
        todoCreateOne: {
          __typename: 'CreateOneTodoPayload',
          recordId: id,
          record: {
            __typename: 'Todo',
            title: 'test12',
            _id: id,
            isOptimistic: true,
          },
        },
      },
      update: (cache, { data: { todoCreateOne } }) => {
        const updates = ApolloCacheUpdater({
          proxy: cache,
          queriesToUpdate: [TODO_MANY],
          operation: {
            type: 'ADD',
            add: ({ query, type, data, variables }) => {
              console.log('Calling Add');
              const rec = todoCreateOne.record;
              return [rec, ...data];
            },
          },
          searchVariables: {},
          mutationResult: todoCreateOne,
          ID: 'recordId',
        });
        if (updates) console.log(`Success`);
      },
    });
  }, []);
```
It is working without @client. "Calling Add" is displaying in console
but when I add @client, add function is not executing.

Note : I also tried doing the cache update manually and it works.

```javascript
        const queryData = cache.readQuery({ query: TODO_MANY });
        cache.writeQuery({
           query: TODO_MANY,
           data: {
             todoMany: [
               ...queryData.todoMany,
               {
                 ...todoCreateOne.record,
               },
             ],
          },
        });
```

Thank you.

**Comment by ecerroni** [comment]
Thanks for reporting this issue. Tbh I never use the @client directive mixed in a remote query, thus I never tested the package for this use case.

It might be that the @client directive, when present, blocks somehow the execution of the function. 

From the documentation, I see that it strips the @client fields from the query before sending it over the network, and then when the results come back, it calculates the @client fields from the local resolvers. Finally, local and network results are merged together.

It could be that ApolloCacheUpdater gets blocked/lost in the process.

Do you have a minimal repository I can use that reproduces the code you posted before?

**Comment by richieroldan** [comment]
Hi @ecerroni,

Here's the link of the repo to replicate the issue.
[REPO](https://github.com/richieroldan/apollo-client-test.git)
I'm using: 

**Server**
- Docker (docker-compose.yml) for mongoDB database server with mongoexpress
- graphql-compose-mongoose [HERE](https://github.com/graphql-compose/graphql-compose-mongoose)
- ExpressJS
- Run ```docker-compose up``` in the /server
- Then ```yarn && yarn start```

**Client**
- React Boilerplate [HERE](https://github.com/react-boilerplate/react-boilerplate)
- Apollo Offline  [HERE](https://www.npmjs.com/package/@wora/apollo-offline)
- Just run ```yarn && yarn start``` in the /client.

The query code is in  ./client/app/containers/HomePage/index.js

 

Thank you so much. Please let me know if you need anything else.

**Comment by ecerroni** [comment]
Thank you for taking the time to put this repo together.

I'll clone it and have a look as soon as I can find some spare time. Unfortunately, I'm slammed with work this month. I'll see what I can do.

**Comment by ecerroni** [comment]
@richieroldan 

I cloned your repo and had a quick look. It seems that you're not using the standard apollo client and that the package you're using (`@wora/apollo-offline`) is not recognizing the client directive

This happens even before you fire the mutation, that is before the apollo-cache-updater gets into the picture. Have a look at the following screenshot:
![image](https://user-images.githubusercontent.com/11174327/73387996-b32eac80-42d1-11ea-8623-be5cc214c6b9.png)

It happens at page load.

**Comment by richieroldan** [comment]
Hi @ecerroni 

Sorry for that, I didn't include the custom resolver for _isOptimistic_ field.

Apollo client should look like this.

```javascript
const client = new ApolloClient({
  link: httpLink,
  cache: new ApolloCache({
    dataIdFromObject: o => o.id,
  }),
  resolvers: {
    Todo: {
      isOptimistic: (obj, args, context) => {
        // console.log('isOptimistic', obj, context.cache);
        if (obj.isOptimistic) {
          return true;
        }
        return false;
      },
    },
  },
});
```

I  pushed the fix in the repo. so you might want to pull it again. Sorry again

And yes I'm using ```@wora/apollo-offline``` but it's using the standard apollo client as well. I'm just utilizing the caching/offline capabilities of  ```@wora/apollo-offline```

You can checkout apollo-offline [here](https://github.com/morrys/wora). 

and for ```@client``` directives here's the [link](https://www.apollographql.com/docs/react/data/local-state/)

Thank you for spending time looking into this issue.

**Comment by ecerroni** [comment]
Thanks for the update.

I confirm that this package has an issue with the `@client` directive. I'll look into it.

**Comment by ecerroni** [comment]
@richieroldan I've pushed v0.1.3 of this package that deals with the `@client` directive.

Once you pull the new version your update function should look like this:
```
      update: (cache, { data: { todoCreateOne } }) => {
        const updates = ApolloCacheUpdater({
          proxy: cache,
          queriesToUpdate: [TODO_MANY],
          operation: {
            type: 'ADD',
            add: ({ query, type, data, variables }) => {
              const rec = todoCreateOne.record;
              if (query === 'todoMany') {
                return [
                  { ...rec, isOptimistic: client.localState.resolvers.Todo.isOptimistic(rec) },
                  ...data,
                ];
              }
            },
          },
          ID: '_id',
          searchVariables: {},
          mutationResult: todoCreateOne.record,
        });
        console.log(updates);
        if (updates) console.log(`Success`);
      },
```

I also updated the readme to include the `@client` directive solution and posted a fully working example with the standard apollo cache [here](https://codesandbox.io/s/apollo-mutations-m5fx0)

Feel free to open again this issue if it is still not working for you.
